substitutions:
  sensor_gpio_left: GPIO10
  sensor_gpio_right: GPIO20
  left_bed_sensor_name: left
  left_bed_sensor_friendly_name: Left
  right_bed_sensor_name: right
  right_bed_sensor_friendly_name: Right

packages:
  diagnostics: !include
    file: ../esphome-common/diagnostics.yaml
    vars:
      boot_gpio: GPIO9
      uptime_id: bed_presence_uptime
      restart_id: btn_restart
      status_id: bed_presence_status

  left_bed_sensor: !include
    file: sensor.yaml
    vars:
      sensor_name: ${left_bed_sensor_friendly_name}
      sensor_id: ${left_bed_sensor_name}
      sensor_gpio: ${sensor_gpio_left}

  right_bed_sensor: !include
    file: sensor.yaml
    vars:
      sensor_name: ${right_bed_sensor_friendly_name}
      sensor_id: ${right_bed_sensor_name}
      sensor_gpio: ${sensor_gpio_right}

binary_sensor:
  - platform: template
    name: Bed Occupied Both (Fast)
    id: bed_occupied_both_fast
    device_class: occupancy
    icon: mdi:bunk-bed
    disabled_by_default: true
    lambda: return id(bed_occupied_${left_bed_sensor_name}_fast).state && id(bed_occupied_${right_bed_sensor_name}_fast).state;

  - platform: template
    name: Bed Occupied Either (Fast)
    id: bed_occupied_either_fast
    device_class: occupancy
    icon: mdi:bunk-bed
    disabled_by_default: true
    lambda: return id(bed_occupied_${left_bed_sensor_name}_fast).state || id(bed_occupied_${right_bed_sensor_name}_fast).state;

  - platform: template
    name: Bed Occupied Both
    id: bed_occupied_both
    device_class: occupancy
    icon: mdi:bunk-bed
    lambda: return id(bed_occupied_${left_bed_sensor_name}).state && id(bed_occupied_${right_bed_sensor_name}).state;

  - platform: template
    name: Bed Occupied Either
    id: bed_occupied_either
    device_class: occupancy
    icon: mdi:bunk-bed
    lambda: return id(bed_occupied_${left_bed_sensor_name}).state || id(bed_occupied_${right_bed_sensor_name}).state;

switch:
  - platform: template
    name: Full Range
    id: full_range
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    entity_category: config
    icon: mdi:arrow-expand

select:
  - platform: template
    name: "Response Speed"
    id: response_speed
    icon: mdi:speedometer
    optimistic: true
    restore_value: true
    options:
      - "Fast"
      - "Normal"
      - "Slow"
    initial_option: "Normal"
    entity_category: config
